[2025-07-20T21:53:15.988+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data permission to 509
[2025-07-20T21:53:15.993+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data'
[2025-07-20T21:53:16.009+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data permission to 509
[2025-07-20T21:53:16.009+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data'
[2025-07-20T21:53:16.032+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_pipeline.aggregate_and_store_pickle_data manual__2025-07-20T21:53:13.527734+00:00 [queued]>
[2025-07-20T21:53:16.036+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_pipeline.aggregate_and_store_pickle_data manual__2025-07-20T21:53:13.527734+00:00 [queued]>
[2025-07-20T21:53:16.037+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-20T21:53:16.044+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): aggregate_and_store_pickle_data> on 2025-07-20 21:53:13.527734+00:00
[2025-07-20T21:53:16.046+0000] {standard_task_runner.py:57} INFO - Started process 119 to run task
[2025-07-20T21:53:16.049+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_pipeline', 'aggregate_and_store_pickle_data', 'manual__2025-07-20T21:53:13.527734+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/fraud_pipeline_dag.py', '--cfg-path', '/tmp/tmp966n1qjk']
[2025-07-20T21:53:16.051+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask aggregate_and_store_pickle_data
[2025-07-20T21:53:16.061+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-20T21:53:16.080+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data permission to 509
[2025-07-20T21:53:16.080+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=fraud_detection_pipeline/run_id=manual__2025-07-20T21:53:13.527734+00:00/task_id=aggregate_and_store_pickle_data'
[2025-07-20T21:53:16.082+0000] {task_command.py:415} INFO - Running <TaskInstance: fraud_detection_pipeline.aggregate_and_store_pickle_data manual__2025-07-20T21:53:13.527734+00:00 [running]> on host da615bb59f10
[2025-07-20T21:53:16.120+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='aggregate_and_store_pickle_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-20T21:53:13.527734+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-20T21:53:13.527734+00:00'
[2025-07-20T21:53:16.121+0000] {fraud_pipeline_dag.py:15} INFO - Reading pickle files from /opt/***/data/data_raw
[2025-07-20T21:53:16.123+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fraud_pipeline_dag.py", line 24, in aggregate_and_store
    raise ValueError(f"No pickle files found in {DATA_FOLDER}")
ValueError: No pickle files found in /opt/***/data/data_raw
[2025-07-20T21:53:16.129+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=fraud_detection_pipeline, task_id=aggregate_and_store_pickle_data, execution_date=20250720T215313, start_date=20250720T215316, end_date=20250720T215316
[2025-07-20T21:53:16.135+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task aggregate_and_store_pickle_data (No pickle files found in /opt/***/data/data_raw; 119)
[2025-07-20T21:53:16.147+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-20T21:53:16.155+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
